version: "3.7"
services:
  application_honey:
    container_name: app_honey
    build:
      context: ../Application
      dockerfile: Dockerfile
    ports: # List of Open Ports Being Honeypotted by the Application
      - "2777:2777"
    depends_on:
      - db_honey
    #restart: unless-stopped

  db_honey:
    container_name: db_honey
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd123!
      #MYSQL_DATABASE: www
      #MYSQL_USER: web
      #MYSQL_PASSWORD: P@ssw0rd
    volumes:
      - "../Database/data:/var/lib/mysql"
      - "../Database/init-sql/build_honeywall_db.sql:/docker-entrypoint-initdb.d/1.sql"
      - "../Database/init-sql/build_www_db.sql:/docker-entrypoint-initdb.d/2.sql"
      - "../Database/init-sql/permissions.sql:/docker-entrypoint-initdb.d/3.sql"
    ports:
      - "3306:3306"
 #   networks:
 #     - web_data
    #restart: unless-stopped

  web_honey:
    container_name: web_honey
    build:
      context: ../Website
      dockerfile: ../Website/Dockerfile
    ports:
      - "8442:80"
      - "8443:443"
#    volumes:
#      - "../Website/node/:/var/www/node"
#      - "../Website/apache:/var/www/apache"
#    networks:
#      - web_data
    restart: unless-stopped
    depends_on:
      - db_honey
#networks:
#  web_data:
#    driver: bridge
