version: "3.7"
services:
  db_honey:
    container_name: db_honey
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd123!
    volumes:
      - "../Database/data:/var/lib/mysql"
      - "../Database/init-sql/build_honeywall_db.sql:/docker-entrypoint-initdb.d/1.sql"
      - "../Database/init-sql/permissions.sql:/docker-entrypoint-initdb.d/3.sql"
    networks:
      - web_data
      - honeywall_data
    restart: unless-stopped
    logging:
      driver: none

  web_honey:
    container_name: web_honey
    build:
      context: ../Website
      dockerfile: ../Website/Dockerfile
    environment:
      - TZ=America/Detroit
      - DB_PASSWORD=xDQKd4wKWJO8YOCT7VALbdCX905DS1p
    ports:
      - "8443:443"
      - "5678:5678"
    volumes:
      - "../Website/apache/:/var/www/apache/"
      - "../Website/raven:/app/"
    networks:
      - web_data
    restart: unless-stopped
    depends_on:
      - db_honey

  application_honey:
    container_name: app_honey
    build:
      context: ../Application
      dockerfile: Dockerfile
    volumes:
      - "../Application/src:/app/"
    environment:
      - TZ=America/Detroit
    ports: # List of Open Ports Being Honeypotted by the Application
      - "2121:21"
      - "2222:22"
      - "2323:23"
      - "8700:80"
#      - "4443:443"
      - "3389:3389"
    depends_on:
      - db_honey
    restart: unless-stopped
    networks:
      - honeywall_data
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  honeywall_data:
    driver: bridge
  web_data:
    driver: bridge
